name:                saz-echo-bot
version:             0.1.0.0
github:              "stanislav-az/saz-echo-bot"
license:             BSD3
author:              "Stanislav Zhdanovich"
maintainer:          "st.zhdanovich@gmail.com"
copyright:           "stanislav-az"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stanislav-az/saz-echo-bot#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- bytestring
- aeson
- mtl
- transformers
- case-insensitive
- time
- text
- configurator
- directory
- unordered-containers
- simple-logger
- filepath
- exceptions

library:
  source-dirs: src

executables:
  saz-echo-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saz-echo-bot

tests:
  saz-echo-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saz-echo-bot
    - hspec
    - QuickCheck
    - quickcheck-instances
    - generic-random
    - http-types
    - http-client
    - tasty
    - tasty-hspec
    